---
version: "3.5"
services:
  app:
   image: 192.168.0.2:5050/dedyms/code-server:v4.0.2
   #image: code-server:local
   #command: code-server --bind-addr 0.0.0.0:8443 --user-data-dir $HOME/code-server --extensions-dir $HOME/code-server/extensions --config $HOME/code-server/config.yaml --disable-telemetry
   #command: bash
   #tty: true
   #stdin_open: true
   #environment:
   #  - HOME=/home/debian
   volumes:
   #  - ./homesmoke:/home/debian
     - ./data:/home/debian/code-server
     - /home/dedyms/Documents/docker-gitlab-local:/home/debian/code-server/docker-gitlab
   #ports:
   #  - 4000:8443
   networks:
     - code-server
   deploy:
     placement:
       constraints: [ node.hostname == homelab  ]
  nginx:
    image: 192.168.0.2:5050/dedyms/nginx:mainline
    ports:
      - 4000:443
    configs:
      - source: default.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - code-server
networks:
  code-server:
    name: code-server
configs:
  default.conf:
    file: ./default.conf
