---
version: "3.5"
services:
  app:
   image: 192.168.0.2:5050/dedyms/code-server:3.12.0
   volumes:
     - ./data:/home/debian
     - /home/dedyms/Documents/docker-gitlab-local:/home/debian/docker-gitlab
   #ports:
   #  - 4000:8443
   networks:
     - codeserver
   deploy:
     placement:
       constraints: [ node.hostname == homelab  ]
  nginx:
    image: 192.168.0.2:5050/dedyms/nginx:mainline
    ports:
      - 4000:443
    configs:
      - source: default.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - codeserver
networks:
  codeserver:
    name: codeserver
configs:
  default.conf:
    file: ./default.conf