version: "3.5"
services:
  cadvisor:
    #image: gcr.io/cadvisor/cadvisor:v0.37.5
    #image: zcube/cadvisor:v0.37.5
    image: 192.168.0.2:5050/dedyms/cadvisor:v0.43
    privileged: true
    networks:
      - tig
    #command: -docker_only
    #command: 
    #  - '--docker_only=true'
      #- '--disable_metrics=disk,network,tcp,udp,percpu,sched,process'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    deploy:
      mode: global
      #placement:
      #  constraints: [ node.platform.arch == x86_64 ]
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M

  node-exporter:
    image: prom/node-exporter:v1.3.1
    networks:
      - tig
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
      - data:/etc/node-exporter
    configs:
      - source: node_entrypoint.sh
        target: /etc/node-exporter/docker-entrypoint.sh
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      #placement:
      #  constraints: [ node.platform.arch == x86_64 ]

  prometheus:
    image: prom/prometheus:v2.32.0
    user: 1000:1000
    networks:
      - tig
    #ports:
    #  - 9000:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-24h}'
    volumes:
      - ./prometheus:/prometheus
    configs:
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yml
      - source: prometheus_conf
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      #resources:
      #  limits:
      #    memory: 2048M
      #  reservations:
      #    memory: 128M

networks:
  tig:
    external: true

volumes:
  data:

configs:
  prometheus_conf:
    file: ./prometheus/conf/prometheus.yml
  node_rules:
    file: ./prometheus/rules/swarm_node.rules.yml
  task_rules:
    file: ./prometheus/rules/swarm_task.rules.yml
  node_entrypoint.sh:
    file: ./node-exporter/conf/docker-entrypoint.sh