services:
   jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: always
    user: 1000:1000
    volumes:
        - ./config:/opt/JDownloader/app/cfg
        - ./Downloads:/opt/JDownloader/Downloads
        - ./logs:/opt/JDownloader/app/logs #optional
        - /etc/localtime:/etc/localtime:ro
    environment: 
            MYJD_USER: dedyms@pm.me
            MYJD_PASSWORD: ayamkampung
            MYJD_DEVICE_NAME: homelab
            XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads #optional
    ports:
        - 3129:3129 
