version: "3.5"
services:
  app:
    image: 192.168.0.2:5050/dedyms/whoogle:latest
    volumes:
      - config:/home/debian/whoogle/config
    environment:
      - WHOOGLE_CONFIG_NEW_TAB=true
      - WHOOGLE_CONFIG_DISABLE=true
      - WHOOGLE_CONFIG_THEME=dark
    #ports:
    #  - 5000:5000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.hostname == rpi4 ]
    networks:
      - whoogle
  nginx:
    image: 192.168.0.2:5050/dedyms/nginx:mainline
    ports:
      - 5000:443
      #- 5001:443
    configs:
      - source: nginx.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - whoogle
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.hostname == rpi4 ]

volumes:
  config:

networks:
  whoogle:
    name: whoogle

configs:
  nginx.conf:
    file: ./nginx.conf
