---
version: '3.5'
services:
  app:
    image: 192.168.0.2:5050/dedyms/ympd:git
    volumes:
      - mpd-data:/home/debian/mpd
      - nfs-dedyms-music:/music
    networks:
      - ympd
    restart: always
    #environment:
    #  MPD_SERVER: player
    #  MPD_PORT: 6600
    ports:
      - "8083:8080"
      - "8800:8800"
    deploy:
      placement:
        constraints:
          - node.hostname == homelab

volumes:
  mpd-data:
  nfs-dedyms-music:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.3,rw,noatime,rsize=8192,wsize=8192,timeo=14,nolock"
      device: ":/home/dedyms/Musik/Music"

networks:
  ympd:
    name: ympd
#  icecast2:
#    external: true
