version: "3.5"
services:
  #fpm:
  # image: 192.168.0.2:5050/dedyms/php-fpm:alpine
   #image: php:8-fpm-alpine
  # environment:
  #   - TZ=Asia/Jakarta
  # volumes:
  #   - nfs-htdocs:/var/www/html
  # networks:
  #   - htmly
  # deploy:
  #   placement:
  #     constraints: [ node.hostname == GITLAB ]
  # restart: unless-stopped
  web:
    image: 192.168.0.2:5050/dedyms/nginx:mainline-fpm
    environment:
      - TZ=Asia/Jakarta
    #configs:
    #  - source: apache.conf
    #    target: /etc/apache2/sites-available/000-default-ssl.conf
    volumes:
      - nfs-htdocs:/var/www/html
    ports:
      #- 6060:80
      - 7171:443
    restart: unless-stopped
    networks:
      - htmly
    deploy:
      placement:
        constraints: [ node.hostname == GITLAB ]
networks:
  htmly:
    name: htmly
  #swag:
  #  external: true
volumes:
  nfs-htdocs:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.3,rw,noatime,timeo=14,nolock"
      device: ":/home/dedyms/docker/htmly/htdocs"

#configs:
#  apache.conf:
#    file: ./apache.conf