---
version: "3.5"
services:
  web:
    image: 192.168.0.2:5050/dedyms/heimdall:git
    networks:
      - heimdall
    volumes:
      - ./db:/var/www/html/database
      - ./storage:/var/www/html/storage
      - ./env:/var/www/html/.env
    deploy:
      placement: 
        constraints: [ node.hostname == homelab ]
    ports:
      - 443:443

networks:
  heimdall:
    name: heimdall
volumes:
   redis-data:
