---
version: "3.5"
services:
  rd:
    image: redis:alpine
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - rd:/data
    restart: unless-stopped
    networks:
      - heimdall
    deploy:
      placement:
        constraints: [node.hostname == homelab ]
  web:
    image: 192.168.0.2:5050/dedyms/heimdall:2.2.3.6
    networks:
      - heimdall
    volumes:
      - db:/var/www/html/database
      - storage:/var/www/html/storage
      - ./env:/var/www/html/.env
    deploy:
      placement: 
        constraints: [ node.role == manager ]
    ports:
      #- 80:80
      - 443:443

networks:
  heimdall:
    name: heimdall

volumes:
  rd:
  storage:
  db:
