version: "3.8"
services:
  app:
    image: 192.168.0.2:5050/dedyms/mariadb:10.6
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - MYSQL_ROOT_PASSWORD=apptestroot
      - TZ=Asia/Jakarta
      - MYSQL_DATABASE=apptest
      - MYSQL_USER=apptest
      - MYSQL_PASSWORD=apptest
    volumes:
      #- ./jellyfin-vue:/home/debian/jellyfin-vue
      #- ./plex:/home/debian/plex
      - ./db:/var/lib/mysql
    #command: bash
    #stdin_open: true
    #tty: true
    networks:
      - apptest
    ports:
      - 25000:3306

networks:
  apptest:
    name: apptest
