version: "3.5"
services:
  es:
    image: elasticsearch:7.17.0
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - TZ=Asia/Jakarta
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
    user: 1000:1000
    ports:
      - 2200:9200
    #  - "1300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      #- nfs-sensei-data:/usr/share/elasticsearch/data
      - ./dataes:/usr/share/elasticsearch/data
      #- ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - diskover
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]
  app:
    image: diskover-app:git
    #command: ["/diskover/crawl.sh"]
    #tty: true
    #stdin_open: true
    environment:
      - TZ=Asia/Jakarta
      - ES_HOST=es
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=changeme
    volumes:
      - /media/WD:/media/WD
      #- ./diskover.cron:/etc/cron.d/diskover
    networks:
      - diskover
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]

  web:
    image: diskover-web:git
    environment:
      - TZ=Asia/Jakarta
    networks:
      - diskover
    #volumes:
      #- htdocs:/var/www/html
      #- ./Constants.php:/var/www/html/src/diskover/Constants.php
    ports:
      - 12000:8000
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]

networks:
  diskover:
    name: diskover

#volumes:
#  htdocs:

#configs:
#  nginx.conf:
#    file: ./diskover-nginx.conf
