version: "3.5"
services:
  app:
    image: 192.168.0.2:5050/dedyms/shepherd:cronjob
    environment:
      APPRISE_SIDECAR_URL: http://notify:8000/notify/
      #NOTIFICATION_URL: discord://816512109075628052/c2Dx2Kz9-rFfqAZ74Wei9Wa2zr8F3sMy0J2K9TVD3bMsxIZY2VQe3o33o0SIShIGa0oM
      WITH_INSECURE_REGISTRY: 'true'
      WITH_REGISTRY_AUTH: 'true'
      NOTIFICATION_URL: discord://853302953162309682/c60wYv390SlEbj7LMo5pHD6SF6y4Pzme4VU57WTlVsngvrnp9kn_kyL0pkC7ynN2lIpk
      AVATAR_URL: https://res.cloudinary.com/dedyms/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1616825895/container/919853_oscoe2.png
      USER: Shepherd
      TZ: 'Asia/Jakarta'
      SLEEP_TIME: '720m'
      BLACKLIST_SERVICES: 'swarm-cronjob_cleanup swarm-cronjob_app shepherd_app apprise_notify swarm-cronjob_buildx-container-cleanup swarm-cronjob_buildx-volume-prune swarm-cronjob_system-prune'
      FILTER_SERVICES: ''
      IMAGE_AUTOCLEAN_LIMIT: ''
      VERBOSE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./daemon.json:/etc/docker/daemon.json
      - /home/dedyms/.docker:/root/.docker:ro
    networks:
      - shepherd
      - apprise
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: none
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 12 * * 0"
        - "swarm.cronjob.skip-running=false"
        - "swarm.cronjob.replicas=1"

networks:
  shepherd:
    name: shepherd
  apprise:
    external: true
