---
version: "3.5"
services:
  prometheus-jeff:
    image: prom/prometheus:v2.31.0
    restart: always
    volumes:
      - ./prometheus-jeff/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    #ports:
    #  - 9090:9090
    networks:
      - jeff
      - tig
    deploy:
      placement:
        constraints: [ node.role == manager  ]

  ping:
    tty: true
    stdin_open: true
    ports:
      - 9115:9115
    image: prom/blackbox-exporter
    restart: always
    configs:
      - source: blackbox.yml
        target: /config/blackbox.yml
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - jeff
    deploy:
      placement:
        constraints: [ node.role == manager  ]

  speedtest:
    ports:
      - 9798:9798
    image: miguelndecarvalho/speedtest-exporter
    restart: always
    networks:
      - jeff
    deploy:
      placement:
        constraints: [ node.role == manager  ]

  nodeexp:
    privileged: true
    image: prom/node-exporter:v1.2.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    #ports:
    #  - 9100:9100
    restart: always
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - jeff
    deploy:
      placement:
        constraints: [ node.role == manager  ]

networks:
  jeff:
    name: jeff
  tig:
    external: true

volumes:
  prometheus_data: {}

configs:
  blackbox.yml:
    file: ./blackbox-config.yml