---
version: "3.5"
services:
  web:
    image: 192.168.0.2:5050/dedyms/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    #ports:
    #  - 7878:7878
    volumes:
      - ./config:/home/debian/radarr
      - /media/WD/Videos/Movies:/Movies
      - nfs-cl-torrents-downloads:/Torrents
    networks:
      - swag
networks:
  swag:
    external: true
volumes:
  #nfs-config:
  #  driver_opts:
  #    type: "nfs4"
  #    o: "addr=192.168.0.2,rw,noatime,timeo=14,nolock,rsize=8192,wsize=8192"
  #    device: ":/home/dedyms/docker/radarr/config"
  nfs-cl-torrents-downloads:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.3,rw,noatime,timeo=14,nolock"
      device: ":/media/Clouds/Downloads/Torrents"
