version: "3.5"
services:
  agent:
    image: crazymax/diun:latest
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/diun.yml:/etc/diun/diun.yml
      - ./data/image.yml:/etc/diun/image.yml
    environment:
      - TZ=Asia/Jakarta
      - LOG_LEVEL=info
      - LOG_JSON=false
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
