version: "3.7"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: --host "tcp://192.168.0.2:2375" --label-enable --notification-url "discord://c2Dx2Kz9-rFfqAZ74Wei9Wa2zr8F3sMy0J2K9TVD3bMsxIZY2VQe3o33o0SIShIGa0oM@816512109075628052"
#https://discord.com/api/webhooks//"
