---
version: "3.5"
services:
  app:
    image: 192.168.0.2:5050/dedyms/icecast2:sid
    ports:
      - 8000:8000
    volumes:
      - config:/home/debian/icecast2
    networks:
      - icecast2
networks:
  icecast2:
    name: icecast2
volumes:
  config:
