version: "3.5"
services:
  db:
    image: 192.168.0.2:5050/dedyms/mariadb:10.5
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lycheeroot
      - TZ=Asia/Jakarta
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=lycheepass
    networks:
      - lychee
    deploy:
      placement:
        constraints: [ node.role == manager ]
  web:
    image: 192.168.0.2:5050/dedyms/lychee:v4.3.6
    volumes:
      - ./uploads:/var/www/html/public/uploads
      - /media/Clouds/InstaSave:/instasave
      - ./env:/var/www/html/.env
      #- ./Lychee:/var/www/html
    networks:
      - lychee
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]
    ports:
      - 4500:443
  rd:
    image: redis:alpine
    volumes:
      - rd-data:/data
    networks:
      - lychee
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]

networks:
  lychee:
    name: lychee
volumes:
  rd-data: