---
version: "3.5"
services:
  web:
    image: ghcr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - AUTO_UPDATE=false
    #ports:
    #  - 9117:9117
    volumes:
      - nfs-jackett-data:/config
      - nfs-cl-downloads:/downloads
    restart: unless-stopped
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]
    networks:
      - jackett
      - swag
volumes:
  nfs-cl-downloads:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.3,rw,noatime,rsize=8192,wsize=8192,timeo=14,nolock"
      device: ":/media/Clouds/Downloads"
  nfs-jackett-data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.3,rw,noatime,rsize=8192,wsize=8192,timeo=14,nolock"
      device: ":/home/dedyms/docker/jackett/config"
networks:
  jackett:
    name: jackett
    driver: overlay
  swag:
    external: true
