---
version: "3.5"
services:
  es:
    image: elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - TZ=Asia/Jakarta
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
    user: 1000:1000
    ports:
      - "1200:9200"
      - "1300:9300"
    volumes:
      #- nfs-sensei-data:/usr/share/elasticsearch/data
      - ./data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - sensei
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == homelab
volumes:
  nfs-sensei-data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.2,rw,noatime,rsize=8192,wsize=8192,timeo=14,nolock"
      device: ":/home/dedyms/docker/opnsensei/data"
networks:
  sensei:
    name: sensei
    driver: overlay
