version: "3.5"
services:
  web:
    image: 192.168.0.2:5050/dedyms/reactive-resume:static
    ports:
      - 7000:80
    networks:
      - reactive-resume
    deploy:
      placement:
        constraints: [ node.hostname == rpi4 ]

networks:
  reactive-resume:
    name: reactive-resume