version: "3.8"
services:
  proxy:
    image: 192.168.0.2:5050/dedyms/nginx:mainline
    ports:
      - 27000:443
      #- 8001:443
    configs:
      - source: nginx.conf
        target: /etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - db
    networks:
      - resume

  app:
    image: 192.168.0.2:5050/dedyms/reactive-resume:v3.2.5
    env_file:
       - env
    networks:
      - resume
    #ports:
    #  - 3000:3000
    #  - 3100:3100

  db:
    image: postgres:13
    user: 1000:1000
    environment:
      - POSTGRES_USER=reactiveresume
      - POSTGRES_PASSWORD=reactiveresumepass
      - POSTGRES_DB=reactiveresume
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - resume
    deploy:
      constraints:
        placement: [ node.role == manager ]

networks:
  apptest:
    name: resume

configs:
  nginx.conf:
    file: nginx.conf