version: "3.8"
services:
  proxy:
    image: 192.168.0.2:5050/dedyms/nginx:mainline
    ports:
      - 27000:443
    configs:
      - source: nginx.conf
        target: /etc/nginx/conf.d/default.conf
#    networks:
#      - resume

  app:
    image: 192.168.0.2:5050/dedyms/reactive-resume:v3.2.8
    env_file:
      - env.v3
    networks:
      - resume
      - default
    deploy:
      placement:
        constraints: [ node.hostname == rpi4 ]

  db:
    image: postgres:13
    user: 1000:1000
    environment:
      - POSTGRES_USER=reactiveresume
      - POSTGRES_PASSWORD=reactiveresumepass
      - POSTGRES_DB=reactiveresume
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - resume
      - default
    deploy:
      placement:
        constraints: [ node.role == manager ]

networks:
  resume:
    name: resume

configs:
  nginx.conf:
    file: nginx.conf
