---
version: '3.8'
services:
  postgresql:
    image: postgres:14
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=authentikpass
      - POSTGRES_USER=authentik
      - POSTGRES_DB=authentik
    env_file:
      - .env
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - goautentik
  redis:
    image: redis:alpine
    restart: unless-stopped
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - goautentik
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.1.4}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentikpass
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      # WORKERS: 2
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
      - geoip:/geoip
    env_file:
      - .env
    ports:
      - "0.0.0.0:${AUTHENTIK_PORT_HTTP:-9500}:9000"
      - "0.0.0.0:${AUTHENTIK_PORT_HTTPS:-9543}:9443"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - goautentik
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2022.1.4}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentikpass
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
    # This is optional, and can be removed. If you remove this, the following will happen
    # - The permissions for the /backups and /media folders aren't fixed, so make sure they are 1000:1000
    # - The docker socket can't be accessed anymore
    user: root
    volumes:
      - ./worker/backups:/backups
      - ./media:/media
      - ./worker/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./custom-templates:/templates
      - geoip:/geoip
    env_file:
      - .env
    networks:
      - goautentik
    deploy:
      placement:
        constraints: [ node.role == manager ]
  geoipupdate:
    image: "maxmindinc/geoipupdate:latest"
    volumes:
      - "geoip:/usr/share/GeoIP"
    environment:
      GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
      GEOIPUPDATE_FREQUENCY: "8"
    env_file:
      - .env
    networks:
      - goautentik
    deploy:
      placement:
        constraints: [ node.role == manager ]

volumes:
  geoip:
    driver: local

networks:
  goautentik:
    name: goautentik
