version: '3.1'
services:
  wordpress:
    image: wordpress:5.9
    restart: always
    ports:
      - 11000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: 192.168.0.2:5050/dedyms/mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspass
      MYSQL_ROOT_PASSWORD: wordpressroot
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
