---
version: "3.5"
services:
  server:
    image: 192.168.0.2:5050/dedyms/glances:latest
    #command: /bin/bash -c "glances -d -s -C $HOME/glances/glances.conf -w"
    #tty: true
    #stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ADDITIONAL_OPT=-d
    ports:
      - "61208:61208"
      #- "61209:61209"
    networks:
      - glances
    deploy:
      placement:
        constraints: [node.role == manager ]
#  client:
#    image: 192.168.0.2:5050/dedyms/glances:latest
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    environment:
#      - ADDITIONAL_OPT=-c server
  #  ports:
  #    - "61209:61209"
#    networks:
#      - glances
#    deploy: 
#      placement:
#        constraints: [node.role != manager ]
networks:
  glances:
    name: glances
    driver: overlay
    internal: true
