version: "3.2"
services:
  buildx-container-cleanup:
    image: docker
    command: ["sh","-c","docker container stop $$(docker container ls -q --filter name=buildx_buildkit*) && docker system prune -f"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 0 * * *"
        - "swarm.cronjob.skip-running=false"
        - "swarm.cronjob.replicas=1"
      restart_policy:
        condition: none
    networks:
      - cronjob
networks:
  cronjob:
    external: true
