---
version: "3.5"
services:
  app:
    image: mango:local
    ports:
      - 2100:9000
    volumes:
      - ./data:/home/debian/mango
      #- ./config.yml:/home/debian/mango/config.yml
      - ./library:/home/debian/mango/library
    networks:
      - mango
networks:
  mango:
    name: mango
