version: "3.5"
services:
  app:
   image: caprover/caprover
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./captain:/captain
   environment:
     - MAIN_NODE_IP_ADDRESS='127.0.0.1'
     - BY_PASS_PROXY_CHECK='TRUE'
   ports:
     - 9090:80
     - 9393:443
     - 9500:3000
   networks:
     - caprover
   deploy:
     placement:
       constraints: [ node.role == manager ]

networks:
  caprover:
    name: caprover
