---
version: '3.5'
services:
  player:
    image: 192.168.0.2:5050/dedyms/mpd:sid
    container_name: mpd
    networks:
      - mpd
      - icecast2
    ports:
      - 8800:8800
      - 6600:6600
    volumes:
      - nfs-dedyms-music:/music
      - ./data:/home/debian/mpd
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == homelab
  #ympd:
  #  image: 192.168.0.2:5050/dedyms/ympd:latest
  #  volumes:
  #    - ./data:/mpd
  #  networks:
  #    - mpd
  #  restart: always
  #  environment:
  #    MPD_SERVER: player
  #    MPD_PORT: 6600
  #  ports:
  #    - "8083:8080"
  #  depends_on:
  #    - player
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.hostname == homelab
volumes:
  #lib:
  nfs-dedyms-music:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.3,rw,noatime,rsize=8192,wsize=8192,timeo=14,nolock"
      device: ":/home/dedyms/Musik/Music"
networks:
  mpd:
    name: mpd
    driver: overlay
  icecast2:
    external: true
