#docker run \
#  -p 9000:9000 \
#  -p 9001:9001 \
#  -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" \
#  -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
#  quay.io/minio/minio server /data --console-address ":9001"

version: "3.5"
services:
  minio:
    image: quay.io/minio/minio
    user: 1000:1000
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioroot
      - MINIO_ROOT_PASSWORD=miniopass
    volumes:
      - ./data:/data
    networks:
      - minio
    command: server /data --console-address ":9001"
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  minio:
    name: minio