version: "3.5"
services:
  web:
    image: alexta69/metube
    container_name: metube
    environment:
      - URL_PREFIX=/metube
    networks:
      - metube
      - swag
    restart: unless-stopped
    user: "1000:1000"
    #ports:
    #  - "8092:8081"
    volumes:
      - nfs-cl-downloads:/downloads
    deploy:
      placement:
        constraints:
          - node.hostname == homelab
volumes:
  nfs-cl-downloads:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.0.3,rw,noatime,rsize=8192,wsize=8192,timeo=14,nolock"
      device: ":/media/Clouds/Downloads"
networks:
  metube:
    name: metube
    driver: overlay
  swag:
    external: true
